version: "3.7"
services:

    api:
        build:
            context: .
            dockerfile: api.dockerfile
        ports:
            - 1323:1323
        depends_on:
            - db
        networks:
            - network
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: database
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
        restart: on-failure

    db:
        build:
            context: .
            dockerfile: db.dockerfile
        ports:
            - 5432:5432
        networks:
            - network
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: database
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: on-failure

volumes:
    pgdata:

networks:
    network:
        driver: bridge