version: '3'
services:

    api:
        build: .
        ports:
            - 1323:1323
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
