name: Docker Publish

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Docker Publish
        uses: manusa/actions-publish-docker@v1.0.1
        with:
          # Name of the Docker image
          name: ${{ secrets.DOCKER_LOGIN }}/hdt-response
          # Username for Docker registry
          username: ${{ secrets.DOCKER_LOGIN }}
          # Password for Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}
